project_name: cob
before:
  hooks:
    - go mod tidy
builds:
  -
    main: .
    binary: cob
    ldflags: 
      - -s -w
      - "-extldflags '-static'"
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
      - openbsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7

nfpms:
  -
    formats:
      - deb
      - rpm
    dependencies:
      - rpm
    vendor: "knqyf263"
    homepage: "https://github.com/knqyf263"
    maintainer: "Teppei Fukuda <knqyf263@gmail.com>"
    description: "Continuous Benchmark for Go Project"
    license: "MIT"
    file_name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "openbsd" }}OpenBSD
      {{- else if eq .Os "netbsd" }}NetBSD
      {{- else if eq .Os "freebsd" }}FreeBSD
      {{- else if eq .Os "dragonfly" }}DragonFlyBSD
      {{- else }}{{ .Os }}{{ end }}-
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "386" }}32bit
      {{- else if eq .Arch "arm" }}ARM
      {{- else if eq .Arch "arm64" }}ARM64
      {{- else }}{{ .Arch }}{{ end }}

archives:
  -
    format: tar.gz
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "openbsd" }}OpenBSD
      {{- else if eq .Os "netbsd" }}NetBSD
      {{- else if eq .Os "freebsd" }}FreeBSD
      {{- else if eq .Os "dragonfly" }}DragonFlyBSD
      {{- else }}{{ .Os }}{{ end }}-
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "386" }}32bit
      {{- else if eq .Arch "arm" }}ARM
      {{- else if eq .Arch "arm64" }}ARM64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE

dockers:
  - image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Tag }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest-amd64'
    dockerfile: goreleaser.Dockerfile
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
  - image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Tag }}-arm'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest-arm'
    dockerfile: goreleaser.Dockerfile
    use: buildx
    goarch: arm
    goarm: 7
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
  - image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Tag }}-arm64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest-arm64'
    dockerfile: goreleaser.Dockerfile
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

docker_manifests:
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Tag }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Tag }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Tag }}-arm'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Tag }}-arm64'
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest-arm'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest-arm64'
